### ISSUE TITLE
ganttlogger-exe-macosでFileNotFoundError: ipaexg.ttf

### ISSUE THREAD

**Issue by KagenoMoheji** [KagenoMoheji/GanttLogger#2]
aloneモードのグラフプロット時に
```
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/4n/8l851g4133d320y_9r6vz18r0000gn/T/_MEIiDpsB0/modules/../config/font/ipaexg.ttf'
```
Pyinstallerでのパッケージングの際に--add-dataしてあるけど、できていない。
`__file__`を使い、その上で相対パスしているのがダメなのしれない？
Windows版では動く。

**Comment by okakyo** [comment]
Mac 上で確認しましたが、ipaexg.ttf　が しっかりインストールされていて、ここで問題が発生しているようには思えませんが。

**Comment by KagenoMoheji** [comment]
pipではなくexeの方で導入してやった？

**Comment by okakyo** [comment]
pip で導入しました。

**Comment by KagenoMoheji** [comment]
pipの方はsetuptoolsでやってるから自動的に含んでくれてるので大丈夫．
でもPyinstallerから作るexeの方は，手動でipaexg.ttfを指定しないといけないんだけど，Macの方でファイルが見つからないとエラーが来て，再パッケージング試してるんだけど，何度やってもできない…

**Comment by KagenoMoheji** [comment]
v0.1.13にて解決．
